[package]
name = "poem-queryext"
version = "0.1.0"
edition = "2021"
description = "Auto deserialize struct from query string"
license = "MIT"
authors = ["cx"]
keywords = ["poem-query-parse"]

[dependencies]
poem = "3.1.7"
serde = "1.0.218"
serde_qs = "0.13.0"
urlencoding = "2.1.3"
